### PR TITLE
Change baseField to bundleField

### PR DESCRIPTION
**Pull request by Fosten**
I raised this issue here: https://github.com/farmOS/farmOS/issues/812 regarding how custom baseFields are not automagically pulled into the default 3.x CSV importers.

It would be nice to CSV import the "calendar" field programmatically, especially in cases where you have many logs you want to import and sync with GCal simultaneously.

Three possible solutions:

1. Hope baseFields will be supported in default farmOS CSV Importers in the future (Didn't sound likely.)
2. Provide custom CSV importers in this module (A lot of extra code, with little value, and subject to change per instance.)
  - ex: https://github.com/Fosten/farm_seed_asset_extended/blob/main/config/install/migrate_plus.migration.farm_seed_asset_extended_csv_import.yml
  - The drawbacks of this:
    - Custom CSV importers would need to be updated whenever any farmOS log fields change.
    - Would need 6+ files that included importers for all the default log bundleFields like (name, timestamp, assets, locations, quantity, quantity measure, quantity units, quantity label, notes, categories, status, equipment, etc.)
   - All files have the same code, with the only difference being default_value for each log_type
```
type:
    plugin: default_value
    default_value: harvest
```
vs
```
type:
    plugin: default_value
    default_value: maintenance
```
  3. Refactor baseField as bundleField (Seems like the easiest fix.)
  - As seen in this PR
  - I've tested this and it works as expected.  Calendar now shows up in the default CSV importers with no extra effort.

### CODE REVIEW

**Comment by Farmer-Eds-Shed** [comment]
@Fosten I'm Ok with this change, I take it there were no issues with existing logs?

**Comment by Fosten** [comment]
Hmm.. good question.  I cannot say with certainty how this effects existing logs, since I was working from a fresh environment.  But I can test this scenario in the coming days.  Perhaps @mstenta @paul121 have some perspective on what/if-any cleanup is needed for converting old baseField entries?

**Comment by mstenta** [comment]
Yea this could be a bit tricky. The main thing to understand is: a "base" field that is not a multi-value field (like this one) will be added as a column to the `log_field_data` table. Whereas a "base" field that is multi-value OR a "bundle" field (of any cardinality) will be added as a separate table.

So, if the `calendar` field is stored as a column in the `log_field_data` table, it will require a careful migration to a separate database table. Can you check your database to see if it's a column of `log_field_data`, or if there is a separate `log__calendar` table? I don't have this installed myself, but looking at the code and knowing how Drupal core works, my guess would be it is a column.

**Comment by Farmer-Eds-Shed** [comment]
Ah..
thanks for the input @mstenta, informative as always.

@Fosten I'm still OK to make the change to the field, if it's going to make things simpler in the long run, but we'll need to figure out any migrations first.

**Comment by Fosten** [comment]
I can confirm for baseField, the calendar column is added to log_field_data.
And for bundleField, log__calendar table is created.

Uninstalling/updating code/reinstalling the module:
- removes the calendar column from log_field_data
- adds the log__calendar table

However, when updating the module without uninstall:
- update the code
- drush cr
- drush updb

```
The website encountered an unexpected error. Try again later.

Drupal\Core\Database\DatabaseExceptionWrapper: Exception in Farm Logs[farm_log]: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "log__calendar" does not exist LINE 3: "log__calendar" "t" ^: SELECT "t".* FROM "log__calendar" "t" WHERE ("entity_id" IN (:db_condition_placeholder_0, :db_condition_placeholder_1, :db_condition_placeholder_2, :db_condition_placeholder_3, :db_condition_placeholder_4, :db_condition_placeholder_5, :db_condition_placeholder_6, :db_condition_placeholder_7, :db_condition_placeholder_8, :db_condition_placeholder_9, :db_condition_placeholder_10, :db_condition_placeholder_11)) AND ("deleted" = :db_condition_placeholder_12) AND ("langcode" IN (:db_condition_placeholder_13, :db_condition_placeholder_14, :db_condition_placeholder_15)) ORDER BY "delta" ASC NULLS FIRST; Array ( [:db_condition_placeholder_0] => 1 [:db_condition_placeholder_1] => 2 [:db_condition_placeholder_2] => 3 [:db_condition_placeholder_3] => 4 [:db_condition_placeholder_4] => 5 [:db_condition_placeholder_5] => 6 [:db_condition_placeholder_6] => 7 [:db_condition_placeholder_7] => 8 [:db_condition_placeholder_8] => 12 [:db_condition_placeholder_9] => 56 [:db_condition_placeholder_10] => 10 [:db_condition_placeholder_11] => 9 [:db_condition_placeholder_12] => 0 [:db_condition_placeholder_13] => en [:db_condition_placeholder_14] => und [:db_condition_placeholder_15] => zxx ) in main() (line 19 of index.php).

Drupal\views\ViewExecutable->execute(NULL) (Line: 1469)
Drupal\views\ViewExecutable->render() (Line: 199)
Drupal\views\Plugin\views\display\Page->execute() (Line: 1645)
Drupal\views\ViewExecutable->executeDisplay('page', Array) (Line: 81)
Drupal\views\Element\View::preRenderViewElement(Array)
call_user_func_array(Array, Array) (Line: 111)
Drupal\Core\Render\Renderer->doTrustedCallback(Array, Array, 'Render #pre_render callbacks must be methods of a class that implements \Drupal\Core\Security\TrustedCallbackInterface or be an anonymous function. The callback was %s. See https://www.drupal.org/node/2966725', 'exception', 'Drupal\Core\Render\Element\RenderCallbackInterface') (Line: 859)
Drupal\Core\Render\Renderer->doCallback('#pre_render', Array, Array) (Line: 421)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 240)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 238)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 627)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 231)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 128)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch(Object, 'kernel.view') (Line: 186)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 76)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 54)
Drupal\simple_oauth\HttpMiddleware\BasicAuthSwap->handle(Object, 1, 1) (Line: 58)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 28)
Drupal\Core\StackMiddleware\ContentLength->handle(Object, 1, 1) (Line: 48)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 36)
Drupal\Core\StackMiddleware\AjaxPageState->handle(Object, 1, 1) (Line: 51)
Drupal\Core\StackMiddleware\StackedHttpKernel->handle(Object, 1, 1) (Line: 704)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
```

To update the module without uninstall:
- I'm thinking a hook_update_N() or hook_post_update_NAME() needs to be implemented
- So that it update re-runs the install script and creates the log__calendar table.

To preserve old data as @mstenta mentioned:
- A migrate script would need to convert the old column into a new table.

And then finally to finish the cleanup:
- Use hook_update_N() to delete the old column from log_field_data.

**Comment by mstenta** [comment]
I think that's right @Fosten.

I think the biggest challenge will be maintaining the `calendar` machine name. I don't think there is any standard way (internal Drupal API functions) to convert a base field to a bundle field. And it's always best to use API functions rather than try to mimic everything manually. I've been burned too many times doing that. So in this case a safer approach would be to create a completely new field, with a new name, migrate the data from the old field, and then delete the old field.

Would we be open to changing it? Maybe it could be called `calendar_update`? That would be a bit more explicit for it's purpose.

This would obviously be a breaking change for this module, because any third-party applications that are reliant on it via the API would need to be updated accordingly. So it would be worth tagging a new major version if you do go this route.

**Comment by mstenta** [comment]
We do have examples in farmOS core of creating new fields via update hooks. We also have an example of a field changing from one type to another (notably from one DATA type to another... not from base to bundle). So it could be possible to keep the `calendar` machine name, following that example. But my gut says it would be safer to migrate to a new field and not try to keep the name. It's also an opportunity to rename the field, if that's worthwhile.

**Comment by Fosten** [comment]
The idea of renaming the field made me consider the https://github.com/mstenta/farm_calendar namespace and potential overlap there.  Not that it would conflict, but rather better to avoid overly general names like "calendar."

Which led me to wonder how viable it would be to join forces and merge the functionality of the two modules?

Essentially, you could have a GUI choice between displaying the https://github.com/mstenta/farm_calendar/blob/1.x/config/install/views.view.farm_calendar.yml
or https://github.com/Farmer-Eds-Shed/farm_calendar_events/blob/main/templates/farm-calendar-events-full-view.html.twig
or both since they are separate menu links.

Just a thought...

**Comment by mstenta** [comment]
> Which led me to wonder how viable it would be to join forces and merge the functionality of the two modules?

IMO these two modules serve different purposes, so it probably makes sense to keep them separate. `farm_calendar` is for displaying a calendar in farmOS, and this one is for syncing farmOS logs to a Google Calendar.

**Comment by Fosten** [comment]
@Farmer-Eds-Shed and @mstenta I've updated this PR with the recommendations above.
- Changed field name from calendar to calendar_update
- Added a hook_update_N to:
  - Install the new calendar_update bundle field
  - Migrate the old calendar base field values
  - Uninstall the old calendar base field
- setInstallVersion so hook_update_N is skipped for new installs

I’ve tested this via /update.php and it works as expected.

There were also revision tables: log_field_revision -> log_revision__calendar_update.
But it didn’t seem necessary to retain revision data.
Plus log_field_revision didn’t have a matching ‘type’ column to convert to a 'bundle’ column.

There are also field_deleted_data_1234567890 and field_deleted_revision_1234567890 tables
after the old calendar base field is uninstalled.
Which I considered removing with field_purge_batch.
But instead left them as is, since they will be removed anyway the next time the user runs cron.

Can you give it a look and let me know if this makes sense or if there’s anything I missed?  Thanks!

**Comment by mstenta** [comment]
> setInstallVersion so hook_update_N is skipped for new installs

This isn't necessary - Drupal keeps track of which update hooks need to be installed or not, and for fresh installs it considers all hooks that exist at the time of installation to be unnecessary.

**Comment by mstenta** [comment]
I haven't tested, but the update hook looks generally correct @Fosten. :+1:

**Comment by Farmer-Eds-Shed** [comment]
This is great work @Fosten,
I'll try and have a better look during the week, cheers!

**Comment by Fosten** [comment]
Updated PR.  Removed hook_install containing setInstalledVersion.

> > setInstallVersion so hook_update_N is skipped for new installs
> 
> This isn't necessary - Drupal keeps track of which update hooks need to be installed or not, and for fresh installs it considers all hooks that exist at the time of installation to be unnecessary.

**Review by Farmer-Eds-Shed — APPROVED** [review]
LGTM

**Pull request merged**
